application: intertubular
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.1"


handlers:

- url: /css
  static_dir: css

- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: intertubular.app
